### ISSUE TITLE
Is it tech blog?

### ISSUE THREAD

**Issue by MaybeS** [HYU-ICEWALL/HYU-ICEWALL.github.io#1]
only for tech blog? not static-page for ICEWALL? @benjioh5

**Comment by benjioh5** [comment]
@MaybeS As you wish. You can find redirect page for ICEWALL static-page (icewall.hyu.ac.kr).

**Comment by MaybeS** [comment]
Is there a repo in HYU-ICEWALL group, publishing web-page (icewall.hyu.ac.kr)?

**Comment by benjioh5** [comment]
Nope. Make it.

**Comment by benjioh5** [comment]
@MaybeS I though you make new repo for ICEWALL static public page and maintain page.
Close issue #1
