### ISSUE TITLE
기존의 ruby로 짜여진 프로젝트는 어떻게 할까요?

### ISSUE THREAD

**Issue by benjioh5** [HYU-ICEWALL/HYU-ICEWALL.github.io#2]
파기? or 재활용? or 냅두기?
https://github.com/HYU-ICEWALL/web

**Comment by MaybeS** [comment]
@devleoper 께서 폐기가 나을꺼같다고 하십니다.
새로운 설계가 필요한데 HYU-ICEWALL project의 Make ICEWALL Great Again을 이용해주세요.
